name: record
description: Audio recorder for Flutter. This plugin provides an easy way to record audio and pick audio files.
version: 4.4.4
homepage: https://github.com/llfbandit/record/tree/master/record

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  record_platform_interface: ^0.5.0
  record_web: ^0.5.0
  record_windows: ^0.7.1
  record_linux: ^0.4.1
  record_macos: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
      ios:
        pluginClass: RecordPlugin
      web:
        default_package: record_web
      windows:
        default_package: record_windows
      linux: 
        default_package: record_linux
      macos:
        default_package: record_macos